### ISSUE TITLE
markdown or similar text area

### ISSUE THREAD

**Issue by Grokmoo** [Grokmoo/thyme#5]
Create a text area like widget that can parse markdown or something similar.  This would be really useful in enabling more complex text layout.

This has the potential to be a performance bottleneck.

**Comment by dumblob** [comment]
>This has the potential to be a performance bottleneck.

It definitely has :wink:. See veteran of font handling and his experience: https://raphlinus.github.io/xi/2020/06/27/xi-retrospective.html (another his blog post about [reactivity and Rust](https://raphlinus.github.io/ui/druid/2019/11/22/reactive-ui.html ) might also come handy in the context of *thyme*).

**Comment by Grokmoo** [comment]
Implemented a basic markdown renderer as of a49a63ebd586435b3a5470a7712a50eb9215d528.  Lots of room for future improvements.
