### ISSUE TITLE
Web compatibility (say Android 9 with default browser)

### ISSUE THREAD

**Issue by dumblob** [Grokmoo/thyme#8]
Is one of the goals of this pretty cool looking library to be web compatible? I mean, can we compile it to JS (or WASM) and make it work **efficiently** (in terms of speed **and** power consumption) in browsers of modestly modern mobile devices (say those having Android 9 or iOS 13)?

Btw. if you'd wanted some more visibility for this project (esp. among potential contributors), I'd be more than happy to add this lib to https://github.com/Immediate-Mode-UI/ organization (it's not an organization per se - there are no rules and no duties - it's just a list of projects considering themself as some sort of immediate mode UI library/app/algorithm).

**Comment by Grokmoo** [comment]
With the WGPU backend we should be able to compile to WASM and render on the web, yes.  Web UI is not of great interest for me personally but I do plan to tackle this at some point.

From a performance perspective I think Thyme (and in general, Immediate Mode UIs) are "good enough" for a typical game.  But it would be very difficult to match the efficiency of a traditional retained state UI.  Maybe with very aggressive caching.  A long term goal perhaps.

**Comment by dumblob** [comment]
Thanks for clarification! I'll close this for the lack of actionable items. Feel free to reopen if you feel so.
